services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    environment:
      OPENAI_API_KEY : ${OPENAI_API_KEY}
      LANGFUSE_API_SK : ${LANGFUSE_API_SK}
      LANGFUSE_API_PK : ${LANGFUSE_API_PK}
    networks:
      - main-network
    depends_on:
      mongo_db:
        condition: service_healthy

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: polytech
      MONGO_INITDB_ROOT_PASSWORD: polytech
      MONGO_INITDB_DATABASE: database
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ~/mongo/data:/data/db
    networks:
      - main-network
    healthcheck:
      test: [ "CMD", "mongosh", "--username", "polytech", "--password", "polytech", "--authenticationDatabase", "admin", "--eval", "db.runCommand('ping').ok" ]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s


networks:
  main-network: