name: Basic Verifications

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LANGFUSE_API_SK: ${{ secrets.LANGFUSE_API_SK }}
      LANGFUSE_API_PK: ${{ secrets.LANGFUSE_API_PK }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Run Spotless check
        run: ./gradlew spotlessCheck

      - name: Run tests
        run: ./gradlew test
